### ISSUE TITLE
Verify SOLR results not decreased by relevance ranking

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#138]
We plan to evaluate Corpus C data for our precision/recall tests, but cn-sandbox-2 contains more data sets than are contained in Corpus C.  We plan to run a variety of SOLR queries, and want to evaluate which data sets from Corpus C are returned from each SOLR query.  SOLR has a relevance ranking algorithm that can be used in determining sort order of the results.  Check to be sure that these algorithms don't have any chance of decreasing the number of results that are matched from the Corpus C set when a broader set of data are present in the index. This should be the case for any arbitrary SOLR query, but we just want to verify.

**Comment by leinfelder** [comment]
I don’t see anything in the FAQ indicates matches will not be returned because of relevance scoring - https://wiki.apache.org/solr/SolrRelevancyFAQ
The first paragraph is somewhat confusing, but the rest of the page does not describe matches dropping off the list if you are sure to retrieve all rows that match.
