### ISSUE TITLE
Change RunManager code to not rely on the cd() command

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#155]
Relying on the current directory can fail based on whether the directory is on the Matlab path or not.  Just pass in directory paths to functions instead, like generateYesWorkflowGraphic().  Remove all calls to cd() in the RunManager.

**Comment by sycao5** [comment]
Pass the directory path to the functions: 
1. captureProspectiveProvenanceWithYW(runManager, runDirectory)
2. generateYesWorkflowGraphic(runManager, runDirectory)
3. buildPackage(runManager, submitter, mnNodeId, dirPath) 

The cd ( ) is used in the function  captureProspectiveProvenanceWithYW( ) because the data/process/combined viewed created by YW not allowing to specify the file path.

The cd( ) is used in the function buildPackage( ) .

**Comment by csjx** [comment]
After thinking about this, we really don't need to pass the path in to functions seperately because the runManager instance has all of the information we need (the provenance_storage_directory and the execution_id) to build the absolute path.

**Comment by sycao5** [comment]
There are two functions captureProspectiveProvenanceWithYW( ) and saveExecution( ) which rely on the cd( ) command. This issue is fixed by the following steps.

1. For captureProspectiveProvenanceWithYW( ) function,

YWConfiguration.getSection( ) can return a hashmap object which stores the configuration settings. We want to pass the full path to the yw view image files. So a full_path_yw_view_image is generated. Then reset the entry with ('dotfile',  full_path_yw_view_image) in the hash map object.


2. For saveExecution( ) function,

We have pass the full path to the execution db file to this function, so there is no need to use cd( ) again.
