### ISSUE TITLE
Create a MemberNode class to wrap and overload the Java MNode methods

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#182]
In issue #156 we need to overload the MN.get(), MN.create(), and MN.update() calls with wrapper functions that will capture provenance.  This ticket provides details for that subtask.
In essence, when a scientist wants to retrieve data from a DataONE Member Node, they must call the MNread.get() REST function.  So far, we haven't exposed this functionality, although it's available through the Java Client Library already.  We need to create an `org.dataone.client.v2.MemberNode` class that will wrap any calls to the Java MNode class.  This class will need to implement all of the public API methods found in the Java MNode class, and wrap them with Matlab-based equivalents.  The Matlab class will need to record provenance statements for each method called.  We need to decide how we will instantiate an MNode.  In the Java library, we use D1Client.getMN().  We may want to mirror this mechanism, or may want to expose an appropriate MemberNode constructor.

**Comment by sycao5** [comment]
The science metadata file has empty local file name in the "Generated" section in the view( ) function. I try to fix this bug by assigning the full-file-path to the fileName in the systemMetadata java object. The issue has not been completely solved because a full-file-name is used in "Generated" section.

Example:

'/Users/syc/.d1/provenance/runs/0b2054d0-fecf-491f-9523-a63b402e94fc/metadata_0b2054d0-fecf-491f-9523-a63b402e94fc.xml'    '721 bytes'    '04-Dec-2015 15:09:12'

**Comment by sycao5** [comment]
Done. More details are now in task #186
