### ISSUE TITLE
Design Provenance Client API configuration system

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/sem-prov-design#42]
WIthin the context of the API for managaing provenance information, investigators need to persist configuration information. Design the configuration system to do so.  Configuration items might include:

- the working directory to store execution information
- the data repository to upload data packages to

And this subsystem might be designed within the provenance client API (issue #41) document.

**Comment by csjx** [comment]
I'm adding Session management API calls to the [Run Manager API](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst) specification based on discussions documented at https://epad.dataone.org/pad/p/2015-02-27-client-run-manager-design.

**Comment by csjx** [comment]
Peter, Yang,
I've updated the [Run Manager API](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst) based on our conversations.  In the set() method, I've listed many of the parameters we think should be configurable, but I think this needs review, and will need additions, but it's a start.
1) I omitted the Execution Config section.  All of these settings are per-run, at run time, so I don't think static settings apply.  Let's touch base on this.
2) For the System Metadata fields that Yang worked on, I omitted:
- archive (this would be set when MN.archive() is called)
- checksumAlgorithm (this is a software impl detail the user doesn't need to know about)
- AccessPolicy (in favor of public_read_allowed)
- ReplicationPolicy (in favor of replication_allowed, number_of_replicas, preferred_replica_node_list, blocked_replica_node_list)
- originMemberNode (in favor of member_node_base_url)
- authoritativeMemberNode (in favor of member_node_base_url)
We may think about adding complex type parameters (like AccessPolicy, replicationPolicy) as JSON object values, but I punted for now.  The origin and authoritative member node IDs can be gained when we know the mn base url and cn base url (since the Node registry in each CN environment is authoritative).
Please review these changes when you have a chance.

**Comment by mbjones** [comment]
Looks good, but one note -- I hope you mean to use the MN node identifiers rather than their base URLs.  The base URLs are transient and can change at any time.  The MN node identifier is persistent (e.g., urn:node:KNB).

**Comment by csjx** [comment]
Good point Matt - I suppose with the `coordinating_node_base_url` we should always be able to look up the `member_node_base_url` from the nodeid.  I'll change this section.

**Comment by sbpcs59** [comment]
@csjx This look great. Should all client implementations use the same file format? I was planning on
storing session info in .csv, as this is more familiar to R users and it can be tricky fixing a JSON file if a needed paren, bracket or quote isn't present.

**Comment by csjx** [comment]
@sbpcs59 I don't think it's all that necessary that every implementation sues the same serialization format.  I'd go with what's convenient and familiar for the language.  We could always revisit it later, if one format seems better than another.

**Comment by csjx** [comment]
I've updated the parameters as Matt suggested above. @sycao5 - You'll need to update the Session class with this change.

**Comment by sycao5** [comment]
i will change the MN_base_url to MN_identifier. Thanks !

**Comment by csjx** [comment]
@sycao5 - Thanks Yang. Note that the new fields are `source_member_node_id` and `target_member_node_id`. I split it into two because I realized in our MsTMIP examples we may be reading data from `urn:node:mnTestMSTMIP`, but may be writing resource maps with provenance information to `urn:node:mnDemo1` because the MsTMIP MN doesn't support the Tier 3 Storage API.

**Comment by sbpcs59** [comment]
@csjx @syscao5 - Do any more changes need to be made to the [Run Manager](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst) API specification? Can I close this issue?

**Comment by csjx** [comment]
@sbpcs59 - I think we can close this. Thanks.

**Comment by sycao5** [comment]
OK. Thanks.

~Yang

**Comment by sbpcs59** [comment]
This specification has been used for the initial versions of both the [matlab toolbox](https://github.com/DataONEorg/matlab-dataone) and the 
[recordr R package](https://github.com/NCEAS/recordr) and appears to be stable. The last update was commit bea613bc1ec9003e6f0ba9ca48e6a378070834de
