### ISSUE TITLE
Compile list of data sets for semantic annotation

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#46]
Generate a specific list of data sets to be annotated using the new knowledge models.  These data should be registered in the semprov test environment (see issue #28), which may require copying them from the current production environments in which they currently reside. Data set list should span both LTER and MsTMIP science scenarios.

**Comment by mobb** [comment]
The list  is checked in here:
https://github.com/DataONEorg/sem-prov-design/blob/master/docs/science-scenarios/example-files/lter/test_corpus_B.txt

Characteristics (test_corpus_B):
server:  cn-sandbox-2.test.dataone.org
source:  LTER generic member node
count:  130 ids from 14 LTER sites

This list is stable, that is, these IDs will not change in D1. We had to wait for issue 90, and the associated bug that was keeping the LTER GMN from contributing.

**Comment by mbjones** [comment]
TODO still:
- [ ] Evaluate whether selection of datasets was biased, and whether that matters to precision recall assessment
- [ ] Define corpus C precisely
- Target April 10th

**Comment by mobb** [comment]
We will have defined several groups of datasets for different purposes; so far we have 3:
corpus A: a short list for developing annotation code. DONE
corpus B: a longer list with general representation across LTER, for ESOR term matching DONE
corpus C: a list for developing query scripts, with ground truth known. DONE

and have planned
corpus D: corpus C + additional datasets with ground truth known. 

We have used the same issue for all of these lists, so it can never be closed. I propose we close this issue since everything it set out to do originally (and was repurposed for) is done.  We would then start a new ticket when a new corpus is needed  - the next one being corpus D (#140)
