### ISSUE TITLE
design and implement annotation store

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#61]
Design and implement an annotation store to store annotations on the CN infrastructure.  This would be deployed in parallel to other CN components as part of the annotation service. For now, this is centralized and stored on CN, later we also may harvest from MN annotations. The store might be as simple as using an existing MN to store the OWL text annotation files, but it might also include an RDF triple store that houses all of the annotations and provides some access capabilities.

**Comment by leinfelder** [comment]
I've been working on this iteratively - first in Metacat as a prototype annotation store for AnnotatorJS objects and now accessible via the CN portal proxying for a user to save to a MN using the standard MN API.
Essentially the workflow for a user adding an annotation would be:
-login to portal (portal now has certificate for the user associated with their session)
-annotate a metadata object in the view UI (currently using Metacat UI with either MN or CN rendering)
-annotation is sent to portal annotation store, which then saves to a [configured?] member node that will store the annotation as a D1 object.
-annotation is harvested by the CN and indexed so that the semantic properties are available in the solr index for discovery purposes.

**Comment by mbjones** [comment]
@leinfelder so where are the annotations actually stored on the server under this model?  That is, what is this 'portal annotation store', how is it implemented, and what is the API for adding annotations to it?  Does it use our create() API like we had discussed?

**Comment by leinfelder** [comment]
The MN stores the annotations (like any other object in dataone). The CN harvests them and indexes them (like any other object in dataone). I just have a servlet that the AnnotatorJS library can interact with for the CRUD operations. The servlet is a translation layer that proxies those requests from the UI to make DataONE MN API calls for creating and modifying annotation objects.
