### ISSUE TITLE
Update DataONE indexer to extract ProvONE traces

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#67]
Provenance traces will be present in ORE documents and multiple other locations. Modify the DataONE indexer to enable it to trigger RDF parsing when a document containing ProvONE triples is encountered.  Initially, trigger this for all ORE documents, and then later for any RDF/OWL document that is typed as ProvONE trace.  Needs discussion as to how we will determine which docunent types might contain these traces.

Extracted provenance traces to be loaded into SOLR.

Consider also whether to load the triples into a persistent triplestore.

**Comment by csjx** [comment]
We are blocked at the moment due to CN synchronization issues with V2 code at the trunk. Sync'ing objects from mn-demo-1 with provenance statements is failing with: 
<pre>
[ERROR] 2015-02-01 19:33:14,403 (TransferObjectTask:processSystemMetadata:441) Task-urn:node:mnDemo1-csj_test_cruncep_monthly_2000_2010_mean_rain_3.nc
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;error detailCode="0000" errorCode="500" name="ServiceFailure"&gt;
    <description>org.dataone.service.types.v1.ObjectFormatList cannot be cast to org.dataone.service.types.v2.ObjectFormatList</description>
&lt;/error&gt;
</pre>
I'm currently trying to track down why this cast is failing.

**Comment by csjx** [comment]
We were also having trouble with synchronization tasks getting NotAuthorized exceptions, even though the CN is presenting its certificate with the request correctly.  Due to Java 7 issues with SNI support, I've temporarily changed the d1-processing daemon to start up with `-Djsse.enableSNIExtension=false`.  mn-demo-1 was showing:
<pre>
metacat 20150131-21:24:10: [WARN]: class org.dataone.client.exception.ClientSideException: No CNs are registered in the NodeLocator [edu.ucsb.nceas.metacat.dataone.D1NodeService]
metacat 20150131-21:24:10: [ERROR]: D1ResourceHandler: Serializing exception with code 401: Not allowed to call synchronizationFailed() on this node. [edu.ucsb.nceas.metacat.restservice.D1ResourceHandler]
org.dataone.service.exceptions.NotAuthorized: Not allowed to call synchronizationFailed() on this node.
	at edu.ucsb.nceas.metacat.dataone.MNodeService.synchronizationFailed(MNodeService.java:1113)
</pre> 
The 'No CNs are registered in the NodeLocator' seemed to indicate that d1_libclient_java was unable to populate the node list, perhaps due to SSL connection issues with the SNI settings.  After restarting Tomcat on the MN (and starting d1-processing with the new parameter), these messages have stopped, and we have no more NotAuthorized exceptions.  For more info, see https://redmine.dataone.org/issues/6787

**Comment by vdave** [comment]
These topics are perhaps more appropriate to put in the Redmine issue tracker for the java client libs:

  https://redmine.dataone.org/projects/java-client

and REST services:

  https://redmine.dataone.org/projects/cn-rest

**Comment by csjx** [comment]
This is done. See https://redmine.dataone.org/issues/6843
