### ISSUE TITLE
evaluate need for bioportal installation

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#71]
We may benefit from having an ontology repository. We currently have 3 choices:

* Use the BioPortal instance and load public or private ontologies into it
* Install our own instance of bioportal on a dataone VM
* Install or create some other ontology store

We need the store mainly as a service to be used by the annotation generator to find matching ontology terms using either the builtin bioportal matching algorithm or additional matching algorithms that we might build.  So, we need to know if bioportal has an extension mechanism to extend its concept matching service.  We can do that by:

1. Email the bioportal devs, describe what we want to do, and ask them if their API has extension points, and what they recommend for us
2. Install their VM image to inspect the code ourselves.

We should start by emailing the developers, and if that doesn't work, then continue with inspecting the code on the VM.

**Comment by leinfelder** [comment]
As of BioPortal v4.14 (released in part by our inquiries) there is an extension point to plugging in an alternative algorithm for concept recommendations. I doubt they would soon accept something we implement as part of their flagship bioportal instance at the ncbo, but we could certainly run our own if we felt committed to maintaining it. My preference is to use their service and not get in the business of running our own ontology repository on DataONE hardware, but if we find their matching algorithm (mgrep-based) to be lacking, then we may be forced to implement something locally.

I don't think there is any harm in using the main bioportal instance for housing all our candidate ontologies since we need broad adoption of the concepts we use in order to do any meaningful synthesis down the road....

**Comment by leinfelder** [comment]
We are not currently planning on supporting our own bioportal installation. Can revisit when we have more experience with ESOR and BioPortal matching service performance.
