### ISSUE TITLE
Determine the mechanism for deciding which types of index processors to invoke

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#72]
Currently, d1_cn_index_processor uses the formatId field in a system metadata document to determine the contents of an object and how it should be indexed into Solr fields using subprocessors.  This may not be fine grain enough, since, for instance, a document with a formatId of rdf/xml might contain concepts from many namespaces, all of which might be processed with several subprocessors.  Determine how to invoke subprocessors (perhaps by namespace occurrence, etc.) for multiple document types.  Also, decide how to merge results from multiple subprocessors into Solr fields. Conflicts are likely to arise.  coordinate with Ben on this since it is the same system for indexing semantic annotations.

**Comment by leinfelder** [comment]
I think the current indexing mechanism can handle this just fine. In the case of RDF/XML, we can have multiple subprocessors configured to handle the same formatId such that each subprocessor knows how to extract the desired information from the model (prov, semantics, data packaging, etc). If we use our triple store like a cache (as Dave wisely suggested) during indexing then we don't incur a penalty for using multiple subprocessors since the same graph will already be loaded with inferencing completed when we use subsequent processors with different SPARQL queries to extract the specific information.

As for merging fields, this is already a consideration in indexing. It's not "smart" but it does work in that a union of all values found for a given [multivalued] field are included in the index. There is not currently a mechanism for deciding which value or set of values is "more correct" than another, though I suppose we could engineer that into the indexing process (based on rightsholder, authMN, or some other combination of values from systemmetadata?)

**Comment by csjx** [comment]
I'm closing this issue since, as Ben pointed out, the current index processing framework accommodates the ability to apply multiple subprocessors.
