### ISSUE TITLE
Decide on which object formats will be used to serialize provenance traces

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#73]
We currently plan to serialize provenance statements into OAI-ORE documents, but also need to consider other stand-alone formats, such as ProvONE instance documents encoded in RDF/XML, Turtle, etc.

**Comment by leinfelder** [comment]
Try all three! It will be a good test of how flexible our indexing system really is. Jena is pretty good about figuring out what to do with an input stream of a model, so we could probably generalize the current RdfXmlSubprocessor to apply to many different serializations since it's all just SPARQL once you have the model loaded in a triplestore.

**Comment by csjx** [comment]
While we can accommodate more than one serialization formats for processing graphs expressed in RDF syntaxes, we are currently focused on resource maps and can extend when necessary. I'll close this, and we can open a new ticket when we decide to use Turtle, JSON-LD, or other formats.
