### ISSUE TITLE
Create semantic relationships between provone:Document and related bibliographic ontology classes

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#76]
The updated ProvONE model extends the prov:Entity class with provone:Data, provone:Visualization, and provone:Document.  a provone:Document refers to published or unpublished documents (scholarly articles, etc.) or reports (government summaries, reports, etc.).  Many bibliographic ontologies already include hierarchies of Documents.  In ProvONe, assert equivalence or other related properties between provone:Document in a judicial manner to be able to leverage the finer granularity of these ontology classes.

**Comment by csjx** [comment]
The `provone:Document` class is basically the same as the `bibo:Document` class.  I've tried asserting the equivalency in the ontology, but it requires a wholesale import of the BIBO Ontology.  I want to confirm that we want to go in this direction before committing.

**Comment by mbjones** [comment]
The import per se isn't the issue. That just includes the statements, but doesn't draw any inferences to them.  However, if we 1) assert that `provone:Document owl:sameAs bibo:Document`, then we have created a strong entailment.  That might be an issue, but I doubt it in this case because bibo:Document is really what we're really aiming for.  Or we could use a weaker similarity statement like `provone:Document moreOrLessEquivalent bibo:Document`, as Mark was describing today, which would have less entailment. 2) An alternate to the sameAs would be for us to say `bibo:Document rdfs:subclassOf prov:Entity` if we want strong inferencing without defining our own ProvONE Document class. That would allow us to make use of it effectively the way we have drawn in our model now, and avoid the cost of defining a somewhat redundant class in provone.  It would also have the advantage of giving us direct access to other BIBO classes and properties, like `bibo:identifier`, `bibo:handle`, `bibo:AcademicArticle`, and `bibo:Image`.  We might want to make `provone:Visualization` a subclass of `bibo:Image` and assert `bibo:Image redfs:sublassOf prov:Entity` (or not, if we think that some Visualizations are not Images).

After all of that, I am leaning towards importing BIBO and using `bibo:Document` directly by asserting its a `prov:Entity`.  I'd love to hear other opinions.

**Comment by csjx** [comment]
After more discussion, we've decided that, given the differing approaches and models used by various communities to describe bibliographic information (like [BIBO](http://bibliographicontology.org) vs [BIBFRAME](http://www.loc.gov/bibframe/)), we don't have consensus on which concepts to equate to or use.  In the interest of finalizing v1 of ProvONE, we'll keep the `provone:document` class, and not equate it to other bibliographic classes.  We will always be able to do so in v2 however.  I'm closing this ticket, but will re-open it when necessary.
