### ISSUE TITLE
Generate ProvONE serializations from Matlab

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#79]
The [DataONE Matlab Toolbox](https://github.com/DataONEorg/matlab-dataone) should be capable of generating ProvONE graph serializations based on the workflow described in a given Matlab scipt (either through YesWorkflow-like comments, or through a configuration object).  This needs design work and other more detailed tickets.  See also https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst

**Comment by ludaesch** [comment]
Hi Chris,

There seem to be two rather different forms of provenance combined in this issue:
(1) Runtime provenance (a.k.a. "retrospective provenance") capture from Matlab
(2) Workflow graphs (a.k.a. "prospective provenance") extracted via YesWorkflow (YW) comments inside of Matlab scripts.

I guess that's why this needs "design work and more tickets". 

* For (2) we can probably make quick progress, given that the YW team already has a working version of the YW prototype.
* For (1), to what extent can we build upon a solution you might have already done for provenance serialization in R?
* Last not least, can we connect this provenance capture and management functionality to a concrete end-user story / use case? For example, there are MsTMIP Matlab scripts that we could look at (in the YW repo such a Matlab script just popped up in the "incoming" folder.

Bertram

**Comment by csjx** [comment]
@ludaesch Yes, I think you've summarized this well.  We will use the provenance work done in R (which implements the Run Manager API) as a guide to doing the same in Matlab.  We will also import the YW Java jar file into the d1_libclient_java project so we can make use of it in Matlab to handle YW-based comments in the scripts.  And, yes, when we write unit tests for the code, we can use the MsTMIP scripts marked up with YW comments as the test scripts, which will make for a well grounded science example.

**Comment by csjx** [comment]
We now produce ProvONE triples inside of the package's resource map using both YesWorkflow comments, and via the overloading of I/O functions.  Closing this ticket.
